
[package]
name = "executor-wasm"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lilyanavalley/exa"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fyrox = {workspace = true}
game = { path = "../game" }
