
name: Scheduled Build

on:
  schedule:
    #? Runs at 2PM everyday.
    # - cron: '0 14 * * *'

    #? Runs every other weekday.
    # - cron: '0 14 * * 1,3,5'

    #? Runs every week on Monday.
    - cron: '0 23 * * 1'
  
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build deps
        run: sudo apt install -y pkg-config libasound2-dev # ALSA required to build.
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2 # Cache build deps for faster building later.
      - name: Run tests
        run: cargo test --verbose

  build_matrix:
    needs: testing
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal

      # Ubuntu requires additional dependencies for build.
      # See: https://fyrox-book.github.io/beginning/scripting.html#platform-specific-dependencies
      - name: Install build dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install -y pkg-config libasound2-dev 
          fi 
        shell: bash

      # Cache build deps for faster building later.
      - uses: Swatinem/rust-cache@v2

      # Compile code
      - name: Build release
        run: cargo build --release --verbose

      # Create installation package for matrix OS.
      - uses: ./.github/workflows/packager.yaml
        with:
          os: ${{ matrix.os }}

      # Makes webtorrents of release
      - name: Make torrent
        uses: devopsx/action-torrent@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            - .git/
            - .vscode/
            - data/
            - editor/
            - executor/
            - executor-*/
            - game/
            - target/**/*(executor*|exa_*)
            - **/Cargo.*
            - **/*.md
            - .gitignore
      
      # Create release
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          files: |
            - .git/
            - .vscode/
            - data/
            - editor/
            - executor/
            - executor-*/
            - game/
            - target/**/*(executor*|exa_*)
            - torrents/
            - **/Cargo.*
            - **/*.md
            - .gitignore
