
name: Scheduled Build

on:
  schedule:
    #? Runs at 2PM everyday.
    # - cron: '0 14 * * *'

    #? Runs every other weekday.
    # - cron: '0 14 * * 1,3,5'

    #? Runs every week on Monday.
    - cron: '0 23 * * 1'

env:
  CARGO_TERM_COLOR: always

jobs:

  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      # Ubuntu requires additional dependencies for build.
      # See: https://fyrox-book.github.io/beginning/scripting.html#platform-specific-dependencies
      - name: Install build dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install -y pkg-config libasound2-dev 
          fi 
        shell: bash
      - name: Build release
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose --workspace
      - uses: ./.github/workflows/packager.yaml
        with:
          os: ${{ matrix.os }}
