
name: Push/Pull Testing

on:
  push:
    branches:
      - "live"
      - "v/*.*.*"
  pull_request:
    branches: [ "live" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

